on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: Node 19.8.1
      uses: actions/setup-node@v1
      with:
        node-version: 19.8.1

    - name: Install and build
      run: |
        npm i
        npm run build

    - name: Run tests
      run: |
        npm run test -- --watch=false --browsers=ChromeHeadless

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.1
      with:
        server: $ {{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PW }}
        local-dir: dist/ringoffire/